### PR TITLE
Add schema module to init for importing

### PR DESCRIPTION
**Pull request by pepe**
This PR adds `schema` module to `spork/init` for convenient import.

### CODE REVIEW

**Comment by pepe** [comment]
I checked the failing test, and it is bizarre as it is in the temple test, which this PR is not touching. On my machine, the test is not failing.

**Comment by sogaiu** [comment]
Similar results here (another Linux box) -- when I try the changes locally, `jpm test` shows "All tests passed.".

**Comment by sogaiu** [comment]
Looking at the error output, may be it's this line here?

https://github.com/janet-lang/spork/blob/master/test/suite0008.janet#L16

**Comment by pepe** [comment]
@sogaiu yep, that I guess is the offending line, but I have no idea why

**Pull request merged**
