### PR TITLE
Fixed typo in probability word

### PR DESCRIPTION
**Pull request by masoodrb**
Fixed typo in probability word

### CODE REVIEW

**Comment by sogaiu** [comment]
Thanks!

**Review by pepe — COMMENTED** [review]
I am only on the phone so I am not sure, but may I ask you if the test code is not affected? I can do it later today.

**Comment by masoodrb** [comment]
@pepe I didn't find any tests using `check-probability` function.

**Comment by masoodrb** [comment]
@pepe BTW could you tell me what is the effective way to run tests for janet projects.
I ran `ls test/*.janet | awk '{ print "janet "$2 }' | sh` to run all janet files in test folder and they all passed.

**Comment by sogaiu** [comment]
@masoodrb If you have `jpm` installed, `jpm test` might work.

**Review by pepe — APPROVED** [review]
LGTM

**Pull request merged**
