### PR TITLE
Added new string module with trim-prefix and trim-suffix

### PR DESCRIPTION
**Pull request by tionis**
I wasn't sure about the module name, please tell me if it doesn't fit.

### CODE REVIEW

**Comment by bakpakin** [comment]
Probably best to just put that in misc. No need for so many individual files.

**Comment by tionis** [comment]
Ok, I moved it into misc

**Review by pepe — CHANGES_REQUESTED** [review]
I think you should add tests for these additions.

**Comment by tionis** [comment]
Fair point, I added two tests for each function

**Comment by sogaiu** [comment]
Minor point -- the docstrings begin with lowercase letters.  May be it's slightly better to use "Trim" rather than "trim"?

**Comment by tionis** [comment]
You're right, I fixed that

**Review by pepe — APPROVED** [review]
Thank you!

**Pull request merged**
