### PR TITLE
added base64 encoder and decoder

### PR DESCRIPTION
**Pull request by tionis**
I added it in its own module, please tell me when I should move it somewhere else in the namespace.  
I also added tests for it.

### CODE REVIEW

**Comment by pepe** [comment]
I had a similar feeling for the PGP words, so I would say misc is ok.

**Review by pepe — CHANGES_REQUESTED** [review]
Please add `assert-docs` to your tests. You will find something I guess. Also, I do not see the reason for docstrings for functions, which are private.

**Comment by tionis** [comment]
I moved the code into misc, fixed the docstrings and added docs

**Comment by tionis** [comment]
I also merged my tests into suite 20 so the tests for misc are grouped together

**Comment by bakpakin** [comment]
Why is this in misc when it could just be in a library "spork/base64"?

I agree with an early observation that spork is already a misc library, so the naming is redundant

**Comment by tionis** [comment]
OK, I moved the code into base64.janet again and also migrated the tests into a new test suite

**Pull request merged**
