### PR TITLE
Use mode argument in make-new-file

### PR DESCRIPTION
**Pull request by sogaiu**
An attempt to address #98.

### CODE REVIEW

**Comment by tionis** [comment]
I'm not sure, mode is means the file open flags, mode normally refers to the permission bits, as far as I recall

**Comment by sogaiu** [comment]
I'm just going by the code that was mostly there already (I think it got put there in https://github.com/janet-lang/spork/commit/ae9db3d5c953d54a0cca74f9352db160e749fce9#diff-addba8464816d2a707000ee1f01e77510dc484a709013f5b62979b3834ef8f11R76) as well as the docs:
```
    (file/open path &opt mode)

    Open a file. `path` is an absolute or relative path, and `mode` is 
    a set of flags indicating the mode to open the file in. `mode` is a 
    keyword where each character represents a flag.
```
Or may be I'm missing something?

**Comment by tionis** [comment]
Oh, I stand corrected, at least in the context of Janet file handling, mode seems to mean exactly what you suggest.

**Review by pepe — APPROVED** [review]
LGTM

**Pull request merged**
