### PR TITLE
allow cfunctions in argparse :map

### LINKED ISSUE #157: in argparse, a cfunction cannot be used for :map
```
(use spork/argparse)
(pp (argparse nil "foo" {:kind :option :map |(scan-number $)})) # returns 3
(pp (argparse nil "foo" {:kind :option :map scan-number})) # returns "3"

```

### PR DESCRIPTION
**Pull request by tionis**
Fixes #157

### CODE REVIEW

**Comment by sogaiu** [comment]
Thanks for this.

On a similar note, I wonder about [this bit](https://github.com/janet-lang/spork/blob/641b27238e073c5f5f963ec16c79b51643d3e66f/spork/argparse.janet#L159).  I'm not too familiar with argparse (^^;

Any thoughts?

**Comment by tionis** [comment]
You mean :action?
This just executes the function at parse time

**Comment by sogaiu** [comment]
I guess so.

The thing is, it's also just checking via only `function?` -- wondering whether it would make sense to change that too.

**Review by pepe — APPROVED** [review]
LGTM

**Comment by pepe** [comment]
> The thing is, it's also just checking via only `function?` -- wondering whether it would make sense to change that too.

This makes sense. Another PR will be fine I guess. Or @tionis do you think you can add it to this one, please?

**Comment by tionis** [comment]
> I guess so.
> 
> The thing is, it's also just checking via only `function?` -- wondering whether it would make sense to change that too.

You're right! I just added the change

**Review by pepe — APPROVED** [review]
LGTM

**Pull request merged**
